---
title: "Iteration exercises"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r}
samp_means <- matrix(NA, nrow = 10, ncol = 3)
ns <- c(3, 5, 10)
for(j in 1:3){
  n <- ns[j]
  for(i in 1:10){
    samp_means[i,j] <- mean(sample(c(1,3,4), size = n, replace = T))
  }
}
```



```{r}
replicate(10, cat("Hello world\n"))

for(i in 1:10){
  cat("Hello world!\n")
}

(1:10) |> map(~ cat("hello world!\n"))

number <- 0
for(i in 1:10){number = number + i}
number

numbers <- c()
number <- 0
for(i in 1:10){number <- number + i; numbers[i] <- number}
numbers

fruits <- c("apple", "banana", "pear")
for(i in 1:3){
  if(fruits[i] == "banana"){
    cat("Found a banana!")
  }
}

```


```{r}
# map exercises
dat <- tibble(n = c(5, 10, 20), mean = 0, sd = 1) # can do an expand_grid
dat %>% 
  mutate(samp = dat |> pmap(rnorm)) -> out 

out |> 
  mutate(samp_mean = map(samp, mean)) # why does this return NULL?

out |> 
  mutate(samp_mean = map_dbl(samp, ~mean(.x))) # but this works.
```

